### ISSUE TITLE
multiplication by zero is not handled correctly

### ISSUE THREAD

**Issue by dgryski** [gonzus/bigint#1]
```
diff --git a/t/020_mul.c b/t/020_mul.c
index f6cafa7..a0e1aa9 100644
--- a/t/020_mul.c
+++ b/t/020_mul.c
@@ -42,6 +42,7 @@ static int test_mul(void)
         {       "45",       "38",             "1710" },
         {       "11",       "34",              "374" },
         {    "76324",     "1234",         "94183816" },
+        { "54760608",        "0",                "0" },
         // large shit
         {
            "348972942347234239482734",
```
fails.

This was discovered with a differential fuzzer: https://github.com/dgryski/trifles/tree/master/bigintfuzz

**Comment by gonzus** [comment]
Hey D, thanks for the issue. I see you keep your hawk eyes :-)

This is just a toy project, but I appreciate it anyway. I just merged a branch where I simplified the whole implementation; the test passes now.

I hope you are keeping healthy and well, wherever you may be. Cheers!

**Comment by dgryski** [comment]
Mostly I wanted to play with writing a differential fuzzer, and this was a good opportunity. :)
